worker_processes auto;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 1024;
}

http {
    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsecurity.conf;

    include /etc/nginx/common.conf;
}
